#' Delta waterways
#'
#' Shapefile of delta waterways
#'
#' @format a sf tibble with 282 rows and 10 columns.
#' \describe{
#'   \item{AREA}{Area.}
#'   \item{PERIMETER}{Perimeter.}
#'   \item{HYDRO_POLY}{HYDRO_POLY.}
#'   \item{HYDRO_PO_1}{HYDRO_PO_1.}
#'   \item{HYDRO_24K_}{HYDRO_24K_.}
#'   \item{HNAME}{HNAME.}
#'   \item{Shape_Leng}{Shape_Length}
#'   \item{Shape_Area}{Shape_Area.}
#'   \item{geometry}{Shapefile polygon coordinates.}
#' }
#' @section Credit:
#' This shapefile was created by the California Department of Fish and Wildlife
"WW_Delta"

#' Bay-Delta regions
#'
#' EDSM regions modified by Brian Mahardja (USFWS)
#'
#' @format a sf tibble with 41 rows and 4 columns.
#' \describe{
#'   \item{Region}{Region}
#'   \item{SubRegion}{SubRegion.}
#'   \item{SQM}{Area of subregion in square miles.}
#'   \item{geometry}{Shapefile polygon coordinates.}
#' }
#' @section Credit:
#' This shapefile was created by the United States Fish and Wildlife Service for the Enhanced Delta Smelt Monitoring Program and modified by Brian Mahardja.
"R_EDSM_Mahardja"

#' Full watershed waterways
#'
#' Shapefile of waterways in the San Francisco Estuary and its watershed
#'
#' @format a sf tibble with 439 rows and 28 columns.
#'
#' @section Credit:
#' This shapefile includes data from CH2M Hill, and Wetland and Water Resources, CDFG Ecosystem Restoration Program as a part of ERP Stage 2 conservation strategy, and Dan Gillenwater.
"WW_Watershed"

#' California Aquatic Resources Inventory wetlands
#'
#' Wetlands habitat data from the California Aquatic Resources Inventory (CARI), cut to only retain feature that touch a 5km buffer around the Bay-Delta (as defined by the \code{\link{WW_Delta}} dataset).
#'
#' @format a sf tibble with 37,135 rows and 18 columns.
#' \describe{
#'   \item{orig_class}{Original classification of the wetland in the source dataset. Source datasets (e.g. NWI, BAARI) use different classification systems. The 'orig_class' field preserves that information.}
#'   \item{name}{The name of a particular wetland feature. (e.g. Alpine Lake).}
#'   \item{globalid}{A placeholder attribute for EcoAtlas.org (unused).}
#'   \item{source_data}{A description of the imagery or other primary data source from which the wetland feature was identified and mapped.}
#'   \item{organization}{The agency or organization that originally mapped the wetland feature.}
#'   \item{orig_dataset}{The original dataset (and data publication date if known) that was integrated into CARI.}
#'   \item{lastupdate}{The date that a particular feature was updated.}
#'   \item{clickcode}{An alphanumeric code for the wetland classification. Clickcode values are undergoing revision and will be updated in a future release of CARI.}
#'   \item{clicklabel}{A detailed description of a feature's wetland type. Clicklabel is the most detailed classification provided by CARI.
#'         Original classifications from component datasets (see 'orig_class'' above) are translated or "crosswalked" into CARI's classification
#'         system. While CARI's component datasets may provide more detail for certain types of wetlands, CARI provides a single
#'         statewide classification for wetland types. E.g. "Depressional Perennial Natural Emergent". Major classes within the 'clicklabel'
#'         field include: wetlands and (deep) open water. Classes and types include: depessions, playas, estuarine, lacustrine. marine,
#'         riverine, lagoon, and slope.}
#'   \item{legcode}{a 1-3 letter code signifying the major wetland class, associated with the 'leglabellevel2' field. Provides less detail than 'clickcode'.}
#'   \item{leglabellevel1}{Common terminology for a feature's wetland type. In EcoAtlas.org, Leglabellevel1 is the value that appears in
#'         the legend, when you click on a particular feature to identify it, and in analyses of wetland area generated by EcoAtlas' Landscape
#'         Profile tool.}
#'   \item{leglabellvel2}{Major classification (less detailed) of the wetland classification provided by the 'clicklabel' field. E.g. "Depressional".}
#'   \item{legend_headings}{In EcoAtlas.org, 'legend_headings' is the value that appears in the legend heading.}
#'   \item{ReleaseDate}{the date that a particular feature was integrated into the CARI dataset, including updated versions of a particular feature.}
#'   \item{CARI_id}{Unique id for that CARI feature.}
#'   \item{Shape_Length}{Length of feature in internal units.}
#'   \item{Shape_Area}{Area of feature in internal units squared.}
#'   \item{Shape}{Geometry column.}
#' }
#' @section Credit:
#' This dataset was created by the San Francisco Estuary Institute and is available (along with full metadata) \href{https://www.sfei.org/data/california-aquatic-resource-inventory-cari-version-03-gis-data}{here}.
"H_CARI_wetlands"

#' California Aquatic Resources Inventory streams
#'
#' Stream data from the California Aquatic Resources Inventory (CARI), cut to only retain feature that touch a 5km buffer around the Bay-Delta (as defined by the \code{\link{WW_Delta}} dataset).
#'
#' @format a sf tibble with 55,522 rows and 16 columns.
#' \describe{
#'   \item{gid}{a placeholder attribute for EcoAtlas.org (unused).}
#'   \item{name}{The name of a particular wetland feature. (e.g. Pajaro River).}
#'   \item{orig_class}{Original classification of the wetland in the source dataset. Source datasets (e.g. NWI, BAARI) use different classification systems. The 'orig_class' field preserves that information.}
#'   \item{source_dat}{a description of the imagery or other primary data source from which the wetland feature was identified and mapped.}
#'   \item{clickcode}{An alphanumeric code for the wetland classification. Clickcode values are undergoing revision and will be updated in a future release of CARI.}
#'   \item{clicklabel}{a detailed description of a feature's wetland type. Clicklabel is the most detailed classification provided by CARI.
#'         Original classifications from component datasets (see 'orig_class'' above) are translated or "crosswalked" into CARI's classification
#'         system. Clicklabel values include: "Fluvial Natural", "Fluvial Unnatural", "Tidal Natural", and "Tidal Unnatural".}
#'   \item{legheader}{In EcoAtlas.org, 'legheader' is the value that appears in the legend heading. "Drainage Features" is the only value for legheader.}.
#'   \item{legcode}{a 1 or 2 letter code identifying whether the major stream class has tidal influence (TR) or not (R), associated with
#'         the 'leglabellevel2' field. Provides less detail than 'clickcode'.}
#'   \item{leglabel}{Common terminology for a feature's wetland type. In EcoAtlas.org, Leglabel is the value that appears in the legend,
#'         when you click on a particular feature to identify it, and in analyses of wetland area generated by EcoAtlas' Landscape Profile tool.
#'         Leglabel values include:"Fluvial" and "Tidal".}
#'   \item{dataset_org}{the agency or organization that originally mapped the wetland feature.}
#'   \item{orig_datas}{the original dataset (and data publication date if known) that was integrated into CARI.}
#'   \item{ReleaseDate}{The date that a particular feature was integrated into the CARI dataset, including updated versions of a particular feature.}
#'   \item{lastupdate}{The date that a particular feature was updated.}
#'   \item{CARI_id}{Unique id for that CARI feature.}
#'   \item{Shape_Length}{Length of feature in internal units.}
#'   \item{Shape}{Geometry column.}
#'
#' }
#' @section Credit:
#' This dataset was created by the San Francisco Estuary Institute and is available (along with full metadata) \href{https://www.sfei.org/data/california-aquatic-resource-inventory-cari-version-03-gis-data}{here}.
"H_CARI_streams"
